### ISSUE TITLE
LSTM_FCN timeseries classification primitive can't be saved

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#102]
```
WARNING - 2019-07-18 06:46:06,999 - v-master-58244dc - distil - Exception running task ID 5d68a141-d428-4ddb-adc3-8217df1cdba4: 'LSTM_FCN' object has no attribute '_params'
Traceback (most recent call last):
  File "/app/main.py", line 136, in exline_task
    save_job(save_me, task.id)
  File "/app/main.py", line 40, in save_job
    pickle.dump(runtime, f)
  File "/usr/local/lib/python3.6/dist-packages/d3m/primitive_interfaces/base.py", line 858, in __getstate__
    'params': self.get_params(),
  File "/src/timeseriesd3mwrappers/TimeSeriesD3MWrappers/LSTM_FCN.py", line 206, in get_params
    return self._params
AttributeError: 'LSTM_FCN' object has no attribute '_params'
```

**Comment by cdbethune** [comment]
NK primitives are erroring during pickling which is what triggers the error, but it turns out there is no reason to pickle and save any more.  Removing that code resolves the issue.
