### ISSUE TITLE
Errors Not Propagating To Client

### ISSUE THREAD

**Issue by phorne-uncharted** [uncharted-distil/distil-auto-ml#117]
It seems as though some errors are not being propagated to the client and outputting status messages stops. When this occurs, a timeout on the client will ultimately end the pipeline processing. Instead, the error should be output as part of a status message so that the client can be made aware of the failure.

ex pipeline:
```
version: "2019.6.11"
allowed_value_types: CSV_URI
template {
  context: TESTING
  name: "wellington"
  inputs {
    name: "inputs"
  }
  outputs {
    name: "outputs 0"
    data: "steps.1.produce"
  }
  steps {
    primitive {
      primitive {
        id: "4b42ce1e-9b98-4a25-b68e-fad13311eb65"
        version: "0.3.0"
        python_path: "d3m.primitives.data_transformation.dataset_to_dataframe.Common"
        name: "Extract a DataFrame from a Dataset"
        digest: "a141e6821de7ae586968b0986237745a5510850e6940cf946db9d50d3828b030"
      }
      arguments {
        key: "inputs"
        value {
          container {
            data: "inputs.0"
          }
        }
      }
      outputs {
        id: "produce"
      }
    }
  }
  steps {
    primitive {
      primitive {
        id: "46612a42-6120-3559-9db9-3aa9a76eb94f"
        version: "1.1.7"
        python_path: "d3m.primitives.data_cleaning.text_summarization.Duke"
        name: "duke"
        digest: "b40cbf3631a19ef0141fb852079330c622b00ef286e54a755e6a90fc85be5963"
      }
      arguments {
        key: "inputs"
        value {
          container {
            data: "steps.0.produce"
          }
        }
      }
      outputs {
        id: "produce"
      }
    }
  }
}
inputs {
  dataset_uri: "file:///tmp/d3m/output/DA_poverty_estimation/TRAIN/dataset_TRAIN/clean/datasetDoc.json"
}
```
has the following error on the TA2 side:
```
ERROR:redirect:/usr/local/lib/python3.6/dist-packages/numpy/core/_methods.py:85: RuntimeWarning: invalid value encountered in double_scalars
ERROR:redirect:  ret = ret.dtype.type(ret / rcount)
WARNING - 2019-10-10 01:49:29,929 - v-master-145e5d8 - distil - Exception running task ID b60ecc6d-7773-4bb3-96d8-ddabbc77b160: Step 1 for pipeline  failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 939, in _do_run_step
    self._run_step(step)
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 929, in _run_step
    self._run_primitive(step)
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 837, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 912, in _call_primitive_method
    raise error
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 908, in _call_primitive_method
    result = method(**arguments)
  File "/usr/local/lib/python3.6/dist-packages/d3m/primitive_interfaces/transformer.py", line 72, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs)
  File "/usr/local/lib/python3.6/dist-packages/d3m/primitive_interfaces/base.py", line 565, in _fit_multi_produce
    produce_results = self._multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/d3m/primitive_interfaces/base.py", line 461, in _multi_produce
    results.append(getattr(self, method_name)(timeout=timeout, iterations=iterations, **arguments))
  File "/app/src/duked3mwrapper/DukeD3MWrapper/wrapper.py", line 166, in produce
    out_tuple = duke.get_top_n_words(N)
  File "/usr/local/lib/python3.6/dist-packages/Duke/dataset_descriptor.py", line 93, in get_top_n_words
    indexed_scores = zip(final_scores, range(len(final_scores)))
TypeError: object of type 'numpy.float64' has no len()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/main.py", line 122, in exline_task
    fitted_pipeline, result = ex_pipeline.fit(pipe, problem_d3m, dataset)
  File "/app/processing/pipeline.py", line 155, in fit
    raise result.error
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 970, in _run
    self._do_run()
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 956, in _do_run
    self._do_run_step(step)
  File "/usr/local/lib/python3.6/dist-packages/d3m/runtime.py", line 948, in _do_run_step
    ) from error
d3m.exceptions.StepFailedError: Step 1 for pipeline  failed.
```
but the TA3 client sees the following messages:
```
[ Oct 10 01:47:32 ] [ INFO ] TA2 GRPC.UNARY [RECV] /Core/SearchSolutions
search_id: "3d5bcdde-ebe5-4f05-b91f-236ac0022edd"
 in 45.67ms (middleware/request_logger.go:128)
[ Oct 10 01:47:32 ] [ INFO ] GRPC.STREAM_CLIENT [SEND] /Core/GetSearchSolutionsResults
search_id: "3d5bcdde-ebe5-4f05-b91f-236ac0022edd"
 (middleware/request_logger.go:128)
[ Oct 10 01:48:33 ] [ INFO ] GRPC.STREAM_CLIENT [RECV] /Core/GetSearchSolutionsResults
progress: <
  state: RUNNING
>
 (middleware/request_logger.go:128)
[ Oct 10 02:18:33 ] [ INFO ] TA2 GRPC.UNARY [SEND] /Core/EndSearchSolutions
search_id: "3d5bcdde-ebe5-4f05-b91f-236ac0022edd"
 (middleware/request_logger.go:128)
[ Oct 10 02:18:33 ] [ INFO ] TA2 GRPC.UNARY [RECV] /Core/EndSearchSolutions
 in 2.14ms (middleware/request_logger.go:128)
[ Oct 10 02:18:33 ] [ ERROR ] unable to run Duke pipeline: error executing pipeline: solution request has timed out (main/main.go:84)
solution request has timed out
```

**Comment by cdbethune** [comment]
I think what's happening here is that the TA2 doesn't handle exceptions thrown during the pipeline execution process in a meaningful way - the run dies and the thread runs until a timeout occurs.
