### ISSUE TITLE
timeseries_kanine exported pipeline is failing

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#253]
`timeseries_kanine` pipeline is include to ensure coverage of the timeseries formatting primitive, but is failing:

```
Traceback (most recent call last):
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1114, in _do_run_step
    self._run_step(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1104, in _run_step
    self._run_primitive(step)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 979, in _run_primitive
    multi_call_result = self._call_primitive_method(primitive.fit_multi_produce, fit_multi_produce_arguments)
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1080, in _call_primitive_method
    raise error
  File "/home/chris/dev/git_work/d3m/d3m/runtime.py", line 1076, in _call_primitive_method
    result = method(**arguments)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/transformer.py", line 71, in fit_multi_produce
    return self._fit_multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, inputs=inputs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 570, in _fit_multi_produce
    produce_results = self._multi_produce(produce_methods=produce_methods, timeout=timeout, iterations=iterations, **kwargs)
  File "/home/chris/dev/git_work/d3m/d3m/primitive_interfaces/base.py", line 466, in _multi_produce
    results.append(getattr(self, method_name)(timeout=timeout, iterations=iterations, **arguments))
  File "/home/chris/dev/git_work/common-primitives/common_primitives/extract_columns_semantic_types.py", line 98, in produce
    columns_to_use = self._get_columns(inputs.metadata)
  File "/home/chris/dev/git_work/common-primitives/common_primitives/extract_columns_semantic_types.py", line 133, in _get_columns
    semantic_types=self.hyperparams['semantic_types'],
ValueError: Input data has no columns matching semantic types: ('https://metadata.datadrivendiscovery.org/types/Target', 'https://metadata.datadrivendiscovery.org/types/TrueTarget')
```

**Comment by cdbethune** [comment]
Targets needed to be passed to the kanine primitive without having been transformed by the satellite image loader.
