### ISSUE TITLE
DB lock errors with large datasets

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#34]
There are DB errors encountered when running with the two largest classification problems - `LL1_336_MS_Geolife_transport_mode_prediction` and `1567_poker_hand`.  It looks like they make it through fit and produce and attempt to return the search results, and fail at that point.

```pre
ERROR - 2019-05-14 11:54:47,220 - v-master-7867e30 - exline.server.ServerServicer - Unexpected error occured, aborting gRPC call: (sqlite3.OperationalError) database is locked
[SQL: SELECT tasks.id AS tasks_id, tasks.search_id AS tasks_search_id, tasks.solution_id AS tasks_solution_id, tasks.fit_solution_id AS tasks_fit_solution_id, tasks.request_id AS tasks_request_id, tasks.type AS tasks_type, tasks.score_config_id AS tasks_score_config_id, tasks.worker_id AS tasks_worker_id, tasks.dataset_uri AS tasks_dataset_uri, tasks.output_key AS tasks_output_key, tasks.pipeline AS tasks_pipeline, tasks.pipeline_run AS tasks_pipeline_run, tasks.problem AS tasks_problem, tasks.created_at AS tasks_created_at, tasks.started_at AS tasks_started_at, tasks.ended AS tasks_ended, tasks.ended_at AS tasks_ended_at, tasks.error AS tasks_error, tasks.error_message AS tasks_error_message
FROM tasks
WHERE tasks.search_id = ? AND tasks.type = ? AND tasks.ended = 1 AND tasks.error = 0 AND 1 = 1
 LIMIT ? OFFSET ?]
[parameters: ('20408544-f852-49ab-b159-5e232e475b6e', 'EXLINE', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/server/server.py", line 49, in _unary_stream_interceptor
    for message in func(request):
  File "/app/server/task_manager.py", line 205, in GetSearchSolutionsResults
    .filter(~models.Tasks.id.in_(seen_ids)) \
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3214, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3006, in __getitem__
    return list(res)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3316, in __iter__
    return self._execute_and_instances(context)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 3341, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/util/compat.py", line 128, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked
[SQL: SELECT tasks.id AS tasks_id, tasks.search_id AS tasks_search_id, tasks.solution_id AS tasks_solution_id, tasks.fit_solution_id AS tasks_fit_solution_id, tasks.request_id AS tasks_request_id, tasks.type AS tasks_type, tasks.score_config_id AS tasks_score_config_id, tasks.worker_id AS tasks_worker_id, tasks.dataset_uri AS tasks_dataset_uri, tasks.output_key AS tasks_output_key, tasks.pipeline AS tasks_pipeline, tasks.pipeline_run AS tasks_pipeline_run, tasks.problem AS tasks_problem, tasks.created_at AS tasks_created_at, tasks.started_at AS tasks_started_at, tasks.ended AS tasks_ended, tasks.ended_at AS tasks_ended_at, tasks.error AS tasks_error, tasks.error_message AS tasks_error_message
FROM tasks
WHERE tasks.search_id = ? AND tasks.type = ? AND tasks.ended = 1 AND tasks.error = 0 AND 1 = 1
 LIMIT ? OFFSET ?]
[parameters: ('20408544-f852-49ab-b159-5e232e475b6e', 'EXLINE', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
```

**Comment by nowfred** [comment]
Going to switch sqlite to run in write-ahead mode because as it turns out, writes should be single threaded

**Comment by cdbethune** [comment]
Not seeing this latest rounds of testing so I think we're good.
