### ISSUE TITLE
vggish_input missing

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#35]
When the latest container is run we get the following error on startup:

```pre

Traceback (most recent call last):
  File "/app/main.py", line 18, in <module>
    from processing import pipeline as ex_pipeline
  File "/app/processing/pipeline.py", line 12, in <module>
    from processing.pipelines import (collaborative_filtering,
  File "/app/processing/pipelines/audio.py", line 16, in <module>
    from exline.primitives.audio_transfer import AudioTransferPrimitive
  File "/usr/local/lib/python3.6/dist-packages/exline/primitives/audio_transfer.py", line 17, in <module>
    from exline.modeling.pretrained_audio import AudiosetModel
  File "/usr/local/lib/python3.6/dist-packages/exline/modeling/pretrained_audio.py", line 19, in <module>
    import vggish_input
ModuleNotFoundError: No module named 'vggish_input'
```

**Comment by jbartonthomas** [comment]
I am looking at it now.
