### ISSUE TITLE
Pod shut down error with text classification 

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#40]
When running the text classification problem with the DMC test script, the pod fails to shutdown upon completion and produces the error below.  A pipeline is produced and if you manually run the test/score phase scores are correctly generated.

```pre
2019-05-15 04:34:56,923:run-log:DEBUG - ['kubectl', 'logs', 'distil-auto-ml-pod', '-n', 'ta3-uncharted', '-c', 'ta2-container']
Traceback (most recent call last):
  File "/performer-toolbox/d3m_runner/d3m_runner.py", line 721, in <module>
    stage_ta2(args, runner)
  File "/performer-toolbox/d3m_runner/d3m_runner.py", line 489, in stage_ta2
    runner.get_pod_log(pod_name=created_pods['pod'], container_name=container["name"])
  File "/performer-toolbox/d3m_runner/d3m_runner.py", line 296, in get_pod_log
    output = subprocess.check_output(cmd, universal_newlines=True).rstrip()
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 405, in run
    stdout, stderr = process.communicate(input, timeout=timeout)
  File "/usr/lib/python3.6/subprocess.py", line 830, in communicate
    stdout = self.stdout.read()
  File "/performer-toolbox/env/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 5592: ordinal not in range(128)
t
```

**Comment by cdbethune** [comment]
This probably needs to be fixed in the `d3m_runner` script rather than our code.  We have some unicode characters in our logs, and the `subprocess_check_output()` function is set to only decode ASCII.

**Comment by jbartonthomas** [comment]
The current text seed dataset (personae) has non-ascii characters. It seems
like setting the runner to process non-ascii text would be a small and
worthwhile adjustment for the program to make.

**Comment by cdbethune** [comment]
It looks like the cluster is configured to use ASCII as its default encoding, and they don't explicitly override that in the calls to `subprocess.get_output`.  I cloned the repo into our namespace on the cluster, set `encoding='UTF-8'` everywhere and it all worked.  I'm going to open an MR against the `d3m_runner` repo.

**Comment by cdbethune** [comment]
https://gitlab.datadrivendiscovery.org/d3m-tools/d3m_runner/merge_requests/3

**Comment by cdbethune** [comment]
PR was merged by DMC.
