### ISSUE TITLE
Search intermittently fails on cluster

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#88]
Periodically we get a failure during search on the cluster yielding the logs below.  It doesn't seem to be triggered by anything in particular, and the `d3m_runner` does cleanup the output directories as a pre-processing step.

```
ta2-uncharted@k8s-jump-server:~/output/logs$ cat id
cat: id: No such file or directory
ta2-uncharted@k8s-jump-server:~/output/logs$ cat distil_auto_ml.log
INFO - 2019-06-14 18:22:46,651 - v-master-1b8b6db - distil - System version master-1b8b6db
INFO - 2019-06-14 18:22:46,651 - v-master-1b8b6db - distil.server.Server - Initializing distil gRPC server
INFO - 2019-06-14 18:22:46,655 - v-master-1b8b6db - distil.server.Server - Started gRPC server, listening for requests
INFO - 2019-06-14 18:22:46,659 - v-master-1b8b6db - distil.server.ServerServicer - Initialized Distil ServerServicer
INFO - 2019-06-14 18:22:46,681 - v-master-1b8b6db - distil.server.Server - Starting server at [::]:45042
DEBUG - 2019-06-14 18:22:46,968 - v-master-1b8b6db - distil.server.ServerServicer - SearchSolutions: user_agent: "test_agent"
version: "2019.6.11"
time_bound_search: 600000.0
priority: 10.0
allowed_value_types: RAW
problem {
  problem {
    task_type: CLASSIFICATION
    task_subtype: BINARY
    performance_metrics {
      metric: F1
      pos_label: "1"
    }
  }
  inputs {
    dataset_id: "30_personae_dataset_TRAIN"
    targets {
      resource_id: "learningData"
      column_index: 6
      column_name: "extrovert"
    }
  }
  id: "30_personae_problem_TRAIN"
  version: "2.0"
  name: "NULL"
  digest: "395aee4673353cb2dc959cfae15c6372fd56bd0bed336acf7f61fb70caadc68f"
}
inputs {
  dataset_uri: "file:///input/TRAIN/dataset_TRAIN/datasetDoc.json"
}
rank_solutions_limit: 20

INFO - 2019-06-14 18:22:46,971 - v-master-1b8b6db - distil.TaskManager - Initialized TaskManager
ERROR - 2019-06-14 18:22:47,066 - v-master-1b8b6db - distil.server.ServerServicer - Unexpected error occured, aborting gRPC call: (sqlite3.OperationalError) no such table: searches
[SQL: INSERT INTO searches (id, created_at, started_at, stopped_at, running, ended, ended_at, error, user_agent, api_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('ac3a5b83-3c46-4dc6-8c09-dfe82c0b3bc0', '2019-06-14 18:22:47.064984', None, None, None, None, None, None, None, None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: searches
```

**Comment by nowfred** [comment]
This seems like a race condition in startup? 

Wonder if we should do a better job mounting the DB directory to a static place

**Comment by cdbethune** [comment]
I'm pretty sure I've got this fixed.  In the app main, we were starting the server, which runs things in its own thread pool, then doing the DB init.  In eval scenarios, where the dummy-ta3 and the ta2 are brought up simultaneously, the ta3 would connect and send a search request, which the now running ta2 server would handle before DB init was complete.  Moving the DB init before starting the server in the main thread should ensure that all the tables are created before any requests are handled.
