### ISSUE TITLE
Tabular regression / classification failures during dry run

### ISSUE THREAD

**Issue by cdbethune** [uncharted-distil/distil-auto-ml#93]
The following are basic tabular regression / classification problems that failed during the June dry run:

196_autoMpg
1567_pokerHand
534_cps_85_wages
LL0_1100_popular_kids
LL1_336_MS_Geolife_transport_mode_prediction_separate_lat_lon
LL1_726_TIDY_GPS_carpool_bus_service_rating_prediction
uu3_world_development_indicators 
uu3_world_development_indicators_raw

We should be able to handle any of these.

**Comment by jbartonthomas** [comment]
LL1_336_MS_Geolife_transport_mode_prediction_separate_lat_lon

**Comment by jbartonthomas** [comment]
196_autoMpg

``` 

INFO - 2019-07-03 22:03:18,995 - v-master-4535f05 - distil.TaskManager - Initialized TaskManager
ERROR - 2019-07-03 22:03:19,007 - v-master-4535f05 - distil.server.ServerServicer - Unexpected error occured, aborting gRPC call: (sqlite3.OperationalError) no such table: searches
[SQL: INSERT INTO searches (id, created_at, started_at, stopped_at, running, ended, ended_at, error, user_agent, api_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('1c47b590-7207-4fb8-84db-429d07dc3ca7', '2019-07-03 22:03:19.006496', None, None, None, None, None, None, None, None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: searches
```

**Comment by jbartonthomas** [comment]
1567_pokerHand

```
INFO - 2019-07-03 21:57:16,890 - v-master-4535f05 - distil.TaskManager - Initialized TaskManager
ERROR - 2019-07-03 21:57:16,943 - v-master-4535f05 - distil.server.ServerServicer - Unexpected error occured, aborting gRPC call: (sqlite3.OperationalError) no such table: searches
[SQL: INSERT INTO searches (id, created_at, started_at, stopped_at, running, ended, ended_at, error, user_agent, api_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('7ded261c-68db-4872-bb1b-7f741708ae93', '2019-07-03 21:57:16.941810', None, None, None, None, None, None, None, None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: searches

```

**Comment by jbartonthomas** [comment]
534_cps_85_wages

```
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: searches
[SQL: INSERT INTO searches (id, created_at, started_at, stopped_at, running, ended, ended_at, error, user_agent, api_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('c2bd4c86-42d6-4a71-83d0-6ffdbd83cca4', '2019-07-03 18:23:52.903535', None, None, None, None, None, None, None, None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-03 18:23:58,734:run-log:DEBUG - Container log for ta3-dummy
2019-07-03 18:23:58,734:run-log:DEBUG - ['kubectl', 'logs', 'ta2-ta3-dummy-pod', '-n', 'eval-dmc-13', '-c', 'ta3-dummy']
2019-07-03 18:23:58,951:run-log:DEBUG - [2019-07-03 18:23:33,072] [INFO] Starting TA2 run
[2019-07-03 18:23:33,072] [INFO] Host localhost
[2019-07-03 18:23:33,075] [INFO] Sending Hello Message
[2019-07-03 18:23:33,076] [WARNING] Hello failed: <_Rendezvous of RPC that terminated with:
```

**Comment by jbartonthomas** [comment]
LL0_1100_popular_kids
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: searches
[SQL: INSERT INTO searches (id, created_at, started_at, stopped_at, running, ended, ended_at, error, user_agent, api_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('00de27b3-b739-42c4-aafc-1b9f8442787c', '2019-07-03 18:03:05.210036', None, None, None, None, None, None, None, None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-03 18:03:08,742:run-log:DEBUG - Container log for ta3-dummy
2019-07-03 18:03:08,742:run-log:DEBUG - ['kubectl', 'logs', 'ta2-ta3-dummy-pod', '-n', 'eval-dmc-14', '-c', 'ta3-dummy']
2019-07-03 18:03:08,899:run-log:DEBUG - [2019-07-03 18:02:54,724] [INFO] Starting TA2 run
[2019-07-03 18:02:54,724] [INFO] Host localhost
[2019-07-03 18:02:54,726] [INFO] Sending Hello Message
[2019-07-03 18:02:54,726] [WARNING] Hello failed: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
```

**Comment by jbartonthomas** [comment]
LL1_726_TIDY_GPS_carpool_bus_service_rating_prediction

```

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: searches
[SQL: INSERT INTO searches (id, created_at, started_at, stopped_at, running, ended, ended_at, error, user_agent, api_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('f8483304-b3ef-435c-a120-3103f361a7f9', '2019-07-03 17:59:17.970932', None, None, None, None, None, None, None, None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-03 17:59:22,370:run-log:DEBUG - Container log for ta3-dummy
2019-07-03 17:59:22,370:run-log:DEBUG - ['kubectl', 'logs', 'ta2-ta3-dummy-pod', '-n', 'eval-dmc-15', '-c', 'ta3-dummy']
2019-07-03 17:59:22,606:run-log:DEBUG - [2019-07-03 17:59:07,906] [INFO] Starting TA2 run
[2019-07-03 17:59:07,906] [INFO] Host localhost
[2019-07-03 17:59:07,908] [INFO] Sending Hello Message
[2019-07-03 17:59:07,909] [WARNING] Hello failed: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "Connect Failed"
```

**Comment by jbartonthomas** [comment]
uu3_world_development_indicators_raw

```
  File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: searches
[SQL: INSERT INTO searches (id, created_at, started_at, stopped_at, running, ended, ended_at, error, user_agent, api_version) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('66c313d7-5416-48f6-8af2-4d62c920e51a', '2019-07-03 21:14:25.961273', None, None, None, None, None, None, None, None)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-03 21:14:31,075:run-log:DEBUG - Container log for ta3-dummy
2019-07-03 21:14:31,075:run-log:DEBUG - ['kubectl', 'logs', 'ta2-ta3-dummy-pod', '-n', 'eval-dmc-21', '-c', 'ta3-dummy']
2019-07-03 21:14:31,368:run-log:DEBUG - [2019-07-03 21:14:10,164] [INFO] Starting TA2 run
[2019-07-03 21:14:10,164] [INFO] Host localhost
[2019-07-03 21:14:10,166] [INFO] Sending Hello Message
[2019-07-03 21:14:10,167] [WARNING] Hello failed: <_Rendezvous of RPC that terminated with:
	status = StatusCode.UNAVAILABLE

```

**Comment by cdbethune** [comment]
Each of those cases are a failure due to the race condition from #88.  It didn't make it into the release that was used for testing, but won't be a problem for the summer eval.
